Mavlink V1 support for routing.
skywaysinc/rust-mavlink pull request #5
Opened 2023-08-13 16:09 UTC by gbin

It is a little ugly but works.

2023-08-20 02:07 UTC, massi31415 requested changes
left few comments !

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +            println!("Raw read UDP");
only for debug no?

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +            println!("Raw read UDP");
otherwise it will spam the user terminal

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +        // raw_msg.patch_sequence::<M>(state.sequence);
Delete?

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +             };
indent?

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +                }
This can be check for V1 too

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +        //*sequence = sequence.wrapping_add(1);
Left over to delete

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> -        *sequence = sequence.wrapping_add(1);
We don't want to patch the seq # here?

2023-08-20 02:07 UTC, massi31415 commented on src/connection/routing.rs
> +            match msg {
I would implement this in the `CommonMessageRaw` trait for the `MAVLinkMessageRaw` type? i.e. add has_valid_crc to the trait

2023-08-20 02:07 UTC, massi31415 commented on src/connection/udp.rs
> +    UdpConnection::new(socket, false, Some(addr), addr.to_string().as_str())
why adding `addr` as str to the args?

2023-08-20 02:07 UTC, massi31415 commented on src/connection/udp.rs
> +    UdpConnection::new(socket, false, Some(addr), addr.to_string().as_str())
Ah I see you redefined the constructor bellow.

2023-08-20 02:07 UTC, massi31415 commented on src/connection/udp.rs
> +    UdpConnection::new(socket, false, Some(addr), addr.to_string().as_str())
It is confusing bit here. Maybe you can put `addr.to_string().as_str()` in a const and give it appropriate naming to explain the functionality i.e. it is an id or something

2023-08-20 02:07 UTC, massi31415 commented on src/lib.rs
> +pub struct MAVLinkAnyMessageRaw<const S: usize>([u8; S]);
I would add the following fields for conveniency: `HEADER_SIZE`, `MAX_SIZE`

2023-08-20 02:07 UTC, massi31415 commented on src/lib.rs
> +pub const MAX_SIZE_V1: usize = 1 + HEADER_SIZE_V1 + 255 + 2;
Let add those to the `MAVLinkV1MessageRaw ` struct and expose them as pub?

2023-08-20 02:07 UTC, massi31415 commented on src/lib.rs
> +pub const MAX_SIZE_V1: usize = 1 + HEADER_SIZE_V1 + 255 + 2;
this means that we need to implement the struct first then the trait

2023-08-20 02:07 UTC, massi31415 commented on src/lib.rs
>      pub fn calculate_crc<M: Message>(&self) -> u16 {
I am wondering how much is the overhead here. Specially at the FC side where compute is limited !

2023-08-20 02:07 UTC, massi31415 commented on src/lib.rs
> +pub type MAVLinkV2MessageRaw = MAVLinkAnyMessageRaw<MAX_SIZE_V2>;
I would add the HEADER_SIZE, MAX_SIZE as fields

2023-09-04 15:11 UTC, gbin commented on src/connection/routing.rs
> +            println!("Raw read UDP");
fixed later

2023-09-04 15:12 UTC, gbin commented on src/connection/routing.rs
> +        // raw_msg.patch_sequence::<M>(state.sequence);
removed later yes, this is breakig mavlink contract for signature

2023-09-04 15:12 UTC, gbin commented on src/connection/routing.rs
> +             };
got fixed with logging

2023-09-04 15:13 UTC, gbin commented on src/connection/routing.rs
> +        //*sequence = sequence.wrapping_add(1);
deleted later

2023-09-04 15:15 UTC, gbin commented on src/lib.rs
> +pub type MAVLinkV2MessageRaw = MAVLinkAnyMessageRaw<MAX_SIZE_V2>;
I just moved them out so it can be reused.

2023-09-04 15:15 UTC, gbin commented on src/lib.rs
>      pub fn calculate_crc<M: Message>(&self) -> u16 {
&mut self.0[(1 + HEADER_SIZE_V1)..(1 + HEADER_SIZE_V1 + payload_length + 2)]  this is almost 0 overhead this is just a view/slice on the message

2023-09-04 15:18 UTC, gbin commented on src/connection/udp.rs
> +    UdpConnection::new(socket, false, Some(addr), addr.to_string().as_str())
Good point, this will be refactored, I hate those string copies everywhere.

2023-09-04 15:19 UTC, merged